### ISSUE TITLE
viz should display path names

### ISSUE THREAD

**Issue by ekg** [vgteam/odgi#33]
This is tricky. We want to be able to see the path names, but this requires directly writing into the PNG image. An alternative is to pull in cairo and write vector graphics over the image. That's also tricky, and introduces more (very complicated and oldschool) dependencies. I'll look into alternatives.

**Comment by josiahseaman** [comment]
One year later, perhaps a better solution is to use Pantograph for interactive browsing.  In our data pipeline we still run odgi viz because it's useful to have a single image to tell if the sort is messed up. 
 But in the long run, An image just can't provide that level of text layout and detail.  I think Pantograph is better used for this than odgi.  We can provide interactive details.because we're in a browser context.  

Also, if you output a file with a sorted array of path names in the same order as the odgi viz rows, then you can use the file to look up the position.  Better yet, if every row is one pixel tall and there's no padding at the top of the image, then the pixel Y value is also the index into this path_name file.
