### ISSUE TITLE
use LMF for sorting

### ISSUE THREAD

**Issue by ekg** [vgteam/odgi#37]
It's been difficult to use topological sorting to get reasonable node orders. It seems that the algorithm has trouble distinguishing tips from actual chromosome starts. An alternative approach would be to sort on the basis of chromosome, which is something that should be implied directly by the graph structures.

An improvement would be to sort the graph using some kind of matrix block diagonal form of its adjacency matrix. Given these matrices are very sparse for genome graphs, we should probably use a method adapted to sparse matrices with good scaling properties. The best-looking implementation I've found is [LMF](https://github.com/evison/LMF). Perhaps there are other, newer ones.

**Comment by josiahseaman** [comment]
Visualization is making ways to improve the sort more obvious.  The first thing we did was sort the rows so that each of the chromosome is stacked up, instead of grouping by individual.  This makes a huge difference and makes transchromosomal rearrangements very obvious as off diagonal.  The next step is to get a sort order that reliably places variation within the context instead of distantly appending it to the end. 

![picturemessage_01hlpqp5 duh](https://user-images.githubusercontent.com/2256148/66827080-e7aa7280-ef45-11e9-9c68-473e17f3e109.png)

There should only be 5 rectangular blocks in this image.  The far right side should be integrated in place.  The vertical bar in the third chromosome seems to be caused by a very tiny overlap in one individual but ignores that it's contiguous with a different chromosome in every other individual.  There doesn't appear to be a "majority vote" in effect.

**Comment by ekg** [comment]
odgi sort has an option to sort the paths by the mean path position. This
should have the same effect as you are looking for. But this doesn't deal
with the sorting of graph nodes.

**Comment by josiahseaman** [comment]
Hi Erik, thanks for your help.  Has there been any improvements to the column sorting?  I'm going to start implementing the next generation of renderer.  I'm depending on the number of links being manageable, which is determined by the column sorting algorithm.  It would be great to see this particular dataset sorted without the blocks on the right shown in the above image.  For testing, here's a download link to the dataset used to generate that image:

https://drive.google.com/drive/folders/1cb5GlQR0BiYJZV0aV93JD-df-9HGBor2?usp=sharing

**Comment by subwaystation** [comment]
@ekg Was this idea superseded by P-SGD?

**Comment by ekg** [comment]
Yes
